//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enderecos
    {
        public int Id { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Bairro { get; set; }
        public string Logradouro { get; set; }
        public string Cep { get; set; }
        public string Localidade { get; set; }
        public string Complemento { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
